#! /usr/bin/env python
# ______________________________________________________________________
"""asdl_py Script

Wrapper script for basil.lang.asdl.asdl_py.

Jonathan Riehl"""
# ______________________________________________________________________
# Module imports

from basil.lang.asdl import asdl_py

# ______________________________________________________________________

if __name__ == "__main__":
    import sys
    asdl_py.main(*sys.argv[1:])

# ______________________________________________________________________
# End of asdl_py
