#! /usr/bin/env python
"""MyFront - Application front end for the Mython compiler.

Jonathan Riehl

$Id$
"""
# ______________________________________________________________________
# Module imports

import sys
from basil.lang.mython.MyFrontUtils import main

# ______________________________________________________________________

if __name__ == "__main__":
    main(*sys.argv[1:])

# ______________________________________________________________________
# End of MyFront
