#define yy_create_buffer cparser_create_buffer
#define yy_delete_buffer cparser_delete_buffer
#define yy_scan_buffer cparser_scan_buffer
#define yy_scan_string cparser_scan_string
#define yy_scan_bytes cparser_scan_bytes
#define yy_flex_debug cparser_flex_debug
#define yy_init_buffer cparser_init_buffer
#define yy_flush_buffer cparser_flush_buffer
#define yy_load_buffer_state cparser_load_buffer_state
#define yy_switch_to_buffer cparser_switch_to_buffer
#define yyin cparserin
#define yyleng cparserleng
#define yylex cparserlex
#define yyout cparserout
#define yyrestart cparserrestart
#define yytext cparsertext
#define yywrap cparserwrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[243] =
    {   0,
        0,    0,   93,   91,   90,   90,   78,   91,    2,   84,
       77,   91,   72,   73,   82,   81,   69,   80,   76,   83,
       38,   38,   70,   66,   85,   71,   86,   89,   35,   35,
       74,   75,   87,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   67,   88,
       68,   79,   65,    0,   43,    0,   51,   68,   60,   52,
        0,    0,   49,   57,   47,   58,   48,   59,    0,   41,
        1,   50,   42,   37,    0,   38,    0,   38,   75,   67,
       74,   56,   62,   64,   63,   55,   35,    0,    0,   53,
       35,   35,   35,   35,   35,   35,   10,   35,   35,   35,

       35,   35,   35,   18,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   54,   61,   39,   44,    0,
       41,   41,    0,   42,   37,    0,   40,   36,   46,   45,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   16,   35,   19,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,    0,
       41,    0,   41,    0,   42,   40,   36,    3,   35,    5,
        6,   35,   35,   35,   35,   12,   13,   35,   35,   17,
       20,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   32,   35,   35,    0,   41,    4,    7,   35,

       35,   35,   35,   15,   35,   35,   23,   35,   35,   35,
       35,   35,   35,   30,   35,   35,   34,   35,   35,   11,
       14,   35,   22,   24,   25,   26,   27,   28,   35,   35,
       35,   35,    9,   35,   29,   35,   35,    8,   21,   31,
       33,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    4,    4,
        4,    4,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[247] =
    {   0,
        0,    0,  372,  373,  373,  373,  348,   60,  373,   43,
       60,  336,  373,  373,  346,   56,  373,   57,   55,   63,
       79,   72,  344,  373,   85,  344,   53,  373,    0,   73,
      373,  373,  343,  310,  312,   78,   43,   38,   54,  313,
       72,  312,  320,   79,  301,  310,  308,  313,  373,   77,
      373,  373,  373,   84,  373,  353,  373,  373,  373,  373,
      107,  122,  373,  373,  373,  373,  373,  373,  339,  124,
      373,  373,  128,  158,  144,  137,    0,  163,  373,  373,
      373,  331,  373,  373,  373,  330,    0,  127,  318,  373,
      297,  309,  296,  311,  298,  304,  290,  291,  288,  288,

      291,  288,  285,    0,  284,  288,   86,  286,  135,   93,
      290,  283,  119,  103,  288,  373,  373,  373,  373,  183,
      373,  189,  196,  373,  190,  168,  204,  194,  373,  373,
      282,  294,  289,  277,  173,  291,  289,  285,  277,  283,
      286,    0,  272,    0,  278,  275,  264,  266,  268,  275,
      261,  259,  259,  271,  261,  265,  269,  271,  260,  210,
      220,  239,  373,  224,  241,  373,  225,    0,  260,    0,
        0,  251,  255,  238,  245,    0,    0,  239,  236,    0,
        0,  234,  234,  231,  243,  232,  236,  240,  239,  236,
      225,  230,    0,  216,  227,  245,  247,    0,    0,  212,

      206,  206,  195,    0,  186,  186,    0,  193,  170,  167,
      149,  156,  156,    0,  142,  138,    0,  125,  119,    0,
        0,  119,    0,    0,    0,    0,    0,    0,  111,  108,
       97,   97,    0,   83,    0,   77,   71,    0,    0,    0,
        0,  373,  294,  298,  300,   67
    } ;

static yyconst short int yy_def[247] =
    {   0,
      242,    1,  242,  242,  242,  242,  242,  243,  242,  242,
      242,  244,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  245,  245,
      242,  242,  242,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  242,  242,
      242,  242,  242,  243,  242,  243,  242,  242,  242,  242,
      244,  244,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  246,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  245,  243,  244,  242,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  246,  242,  242,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  242,
      242,  242,  242,  242,  242,  242,  242,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  242,  242,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,    0,  242,  242,  242,  242
    } ;

static yyconst short int yy_nxt[438] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   29,   30,
       29,   29,   31,    4,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   29,   41,   29,   42,   29,   29,   29,
       29,   43,   44,   45,   46,   47,   48,   29,   29,   29,
       49,   50,   51,   52,   55,   57,   58,   59,   64,  128,
       69,   66,   70,   70,   71,   85,   86,   88,   65,   67,
       68,   89,   60,   96,   98,   72,   99,   73,   55,   78,
       78,   80,   97,   56,   73,  100,   74,   74,   75,  116,

      101,   76,   76,  102,   81,   75,   82,   83,   76,   76,
       77,  241,   75,  104,   93,  118,  240,   56,   76,   75,
      105,   94,  108,  109,  242,   76,   76,   95,  146,  151,
       61,   55,  110,   76,  239,  111,   77,  238,  117,  147,
       62,   70,   70,  237,  152,  122,  122,  157,  236,  158,
      120,  121,  235,  121,  123,  124,  126,  124,  126,  234,
       56,  127,  127,  155,  120,  121,   76,   76,  123,  124,
      121,  156,  233,   73,  124,   74,   74,  149,   73,  232,
       78,   78,  231,   76,   75,  127,  127,  125,  125,   75,
      230,   76,   76,   76,  150,  160,  229,  160,   75,  228,

      161,  161,  227,   75,  125,  226,  122,  122,  164,   76,
      164,  225,  125,  165,  165,  162,  163,   76,  163,  125,
      125,  127,  127,  167,  167,  172,  173,  161,  161,  162,
      163,  166,  224,  166,  223,  163,  125,  161,  161,  222,
      167,  165,  165,  221,  125,  166,  220,  121,  167,  121,
      166,  196,  219,  196,  167,  167,  197,  197,  165,  165,
      218,  121,  197,  197,  197,  197,  121,  217,  124,  216,
      124,  167,  215,  214,  163,  213,  163,  212,  211,  167,
      210,  209,  124,  208,  207,  206,  205,  124,  163,  204,
      203,  202,  201,  163,   54,   54,   54,   54,   61,  200,

       61,   61,   87,   87,  199,  198,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  171,  170,
      169,  168,  159,  154,  153,  148,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,
      131,   62,  130,  129,  119,  242,  115,  114,  113,  112,
      107,  106,  103,   92,   91,   90,   84,   79,   63,   62,
       53,  242,    3,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242
    } ;

static yyconst short int yy_chk[438] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   10,   10,   11,   16,  246,
       19,   18,   19,   19,   20,   27,   27,   30,   16,   18,
       18,   30,   11,   37,   38,   20,   38,   22,   54,   22,
       22,   25,   37,    8,   21,   38,   21,   21,   22,   50,

       39,   22,   22,   39,   25,   21,   25,   25,   21,   21,
       21,  237,   22,   41,   36,   61,  236,   54,   22,   21,
       41,   36,   44,   44,   62,   21,   22,   36,  107,  110,
       62,   88,   44,   21,  234,   44,   21,  232,   50,  107,
       61,   70,   70,  231,  110,   73,   73,  114,  230,  114,
       70,   70,  229,   70,   73,   73,   75,   73,   75,  222,
       88,   75,   75,  113,   70,   70,   76,   76,   73,   73,
       70,  113,  219,   74,   73,   74,   74,  109,   78,  218,
       78,   78,  216,   76,   74,  126,  126,   74,   74,   78,
      215,   76,   78,   78,  109,  120,  213,  120,   74,  212,

      120,  120,  211,   78,   74,  210,  122,  122,  123,   78,
      123,  209,   74,  123,  123,  122,  122,   78,  122,  125,
      125,  127,  127,  128,  128,  135,  135,  160,  160,  122,
      122,  127,  208,  127,  206,  122,  125,  161,  161,  205,
      128,  164,  164,  203,  125,  127,  202,  161,  128,  161,
      127,  162,  201,  162,  167,  167,  162,  162,  165,  165,
      200,  161,  196,  196,  197,  197,  161,  195,  165,  194,
      165,  167,  192,  191,  197,  190,  197,  189,  188,  167,
      187,  186,  165,  185,  184,  183,  182,  165,  197,  179,
      178,  175,  174,  197,  243,  243,  243,  243,  244,  173,

      244,  244,  245,  245,  172,  169,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  143,  141,  140,  139,  138,  137,  136,  134,  133,
      132,  131,  115,  112,  111,  108,  106,  105,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   89,   86,   82,   69,   56,   48,   47,   46,   45,
       43,   42,   40,   35,   34,   33,   26,   23,   15,   12,
        7,    3,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cparser.l"
#define INITIAL 0
/* ______________________________________________________________________
   cparser.l
   $Id: cparser.l,v 1.2 2003/07/02 21:59:38 jriehl Exp $
   ______________________________________________________________________ */
/* This Lex specification is based on the Lex specification by Jutta Degener
 * (1995), http://www.lysator.liu.se/c/ANSI-C-grammar-y.html, which
 * was derived from a Lex specification of Jeff Lee.
*/
#line 19 "cparser.l"
#include <stdio.h>
#include "cparserutils.h"
#include "namespace.h"

#define YYSTYPE CParserNode*

#include "cparser.tab.h"

static void CParserCount(TokenType tt);
static void CParserComment();
static void CParserHash();
static int CParserCheckType();

#line 581 "lex.cparser.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 34 "cparser.l"

#line 734 "lex.cparser.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 243 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 373 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "cparser.l"
{ CParserComment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "cparser.l"
{ CParserHash(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "cparser.l"
{ CParserCount(TT_AUTO); return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "cparser.l"
{ CParserCount(TT_BREAK); return(BREAK); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "cparser.l"
{ CParserCount(TT_CASE); return(CASE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "cparser.l"
{ CParserCount(TT_CHAR); return(CHAR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "cparser.l"
{ CParserCount(TT_CONST); return(CONST); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "cparser.l"
{ CParserCount(TT_CONTINUE); return(CONTINUE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "cparser.l"
{ CParserCount(TT_DEFAULT); return(DEFAULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "cparser.l"
{ CParserCount(TT_DO); return(DO); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "cparser.l"
{ CParserCount(TT_DOUBLE); return(DOUBLE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "cparser.l"
{ CParserCount(TT_ELSE); return(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "cparser.l"
{ CParserCount(TT_ENUM); return(ENUM); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "cparser.l"
{ CParserCount(TT_EXTERN); return(EXTERN); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "cparser.l"
{ CParserCount(TT_FLOAT); return(FLOAT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "cparser.l"
{ CParserCount(TT_FOR); return(FOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "cparser.l"
{ CParserCount(TT_GOTO); return(GOTO); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "cparser.l"
{ CParserCount(TT_IF); return(IF); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "cparser.l"
{ CParserCount(TT_INT); return(INT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "cparser.l"
{ CParserCount(TT_LONG); return(LONG); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "cparser.l"
{ CParserCount(TT_REGISTER); return(REGISTER); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "cparser.l"
{ CParserCount(TT_RETURN); return(RETURN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "cparser.l"
{ CParserCount(TT_SHORT); return(SHORT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "cparser.l"
{ CParserCount(TT_SIGNED); return(SIGNED); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "cparser.l"
{ CParserCount(TT_SIZEOF); return(SIZEOF); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "cparser.l"
{ CParserCount(TT_STATIC); return(STATIC); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "cparser.l"
{ CParserCount(TT_STRUCT); return(STRUCT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "cparser.l"
{ CParserCount(TT_SWITCH); return(SWITCH); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "cparser.l"
{ CParserCount(TT_TYPEDEF); return(TYPEDEF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "cparser.l"
{ CParserCount(TT_UNION); return(UNION); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "cparser.l"
{ CParserCount(TT_UNSIGNED); return(UNSIGNED); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "cparser.l"
{ CParserCount(TT_VOID); return(VOID); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "cparser.l"
{ CParserCount(TT_VOLATILE); return(VOLATILE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "cparser.l"
{ CParserCount(TT_WHILE); return(WHILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "cparser.l"
{ CParserCount(TT_IDENTIFIER);
                          return(CParserCheckType()); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "cparser.l"
{ CParserCount(TT_CONSTANT); return(CONSTANT); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "cparser.l"
{ CParserCount(TT_CONSTANT); return(CONSTANT); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "cparser.l"
{ CParserCount(TT_CONSTANT); return(CONSTANT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "cparser.l"
{ CParserCount(TT_CONSTANT); return(CONSTANT); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "cparser.l"
{ CParserCount(TT_CONSTANT); return(CONSTANT); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "cparser.l"
{ CParserCount(TT_CONSTANT); return(CONSTANT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "cparser.l"
{ CParserCount(TT_CONSTANT); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "cparser.l"
{ CParserCount(TT_STRING_LITERAL);
                          return(STRING_LITERAL); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 86 "cparser.l"
{ CParserCount(TT_ELLIPSIS); return(ELLIPSIS); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 87 "cparser.l"
{ CParserCount(TT_RIGHT_ASSIGN);
                          return(RIGHT_ASSIGN); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "cparser.l"
{ CParserCount(TT_LEFT_ASSIGN); return(LEFT_ASSIGN); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "cparser.l"
{ CParserCount(TT_ADD_ASSIGN); return(ADD_ASSIGN); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "cparser.l"
{ CParserCount(TT_SUB_ASSIGN); return(SUB_ASSIGN); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "cparser.l"
{ CParserCount(TT_MUL_ASSIGN); return(MUL_ASSIGN); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "cparser.l"
{ CParserCount(TT_DIV_ASSIGN); return(DIV_ASSIGN); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "cparser.l"
{ CParserCount(TT_MOD_ASSIGN); return(MOD_ASSIGN); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "cparser.l"
{ CParserCount(TT_AND_ASSIGN); return(AND_ASSIGN); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "cparser.l"
{ CParserCount(TT_XOR_ASSIGN); return(XOR_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "cparser.l"
{ CParserCount(TT_OR_ASSIGN); return(OR_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "cparser.l"
{ CParserCount(TT_RIGHT_OP); return(RIGHT_OP); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "cparser.l"
{ CParserCount(TT_LEFT_OP); return(LEFT_OP); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "cparser.l"
{ CParserCount(TT_INC_OP); return(INC_OP); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "cparser.l"
{ CParserCount(TT_DEC_OP); return(DEC_OP); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "cparser.l"
{ CParserCount(TT_PTR_OP); return(PTR_OP); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "cparser.l"
{ CParserCount(TT_AND_OP); return(AND_OP); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "cparser.l"
{ CParserCount(TT_OR_OP); return(OR_OP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "cparser.l"
{ CParserCount(TT_LE_OP); return(LE_OP); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "cparser.l"
{ CParserCount(TT_GE_OP); return(GE_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "cparser.l"
{ CParserCount(TT_EQ_OP); return(EQ_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "cparser.l"
{ CParserCount(TT_NE_OP); return(NE_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "cparser.l"
{ CParserCount(TT_SEMICOLON); return(';'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "cparser.l"
{ CParserCount(TT_LBRACE); return('{'); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "cparser.l"
{ CParserCount(TT_RBRACE); return('}'); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "cparser.l"
{ CParserCount(TT_COMMA); return(','); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 113 "cparser.l"
{ CParserCount(TT_COLON); return(':'); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 114 "cparser.l"
{ CParserCount(TT_EQUAL); return('='); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 115 "cparser.l"
{ CParserCount(TT_LPAREN); return('('); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 116 "cparser.l"
{ CParserCount(TT_RPAREN); return(')'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 "cparser.l"
{ CParserCount(TT_LBRACK); return('['); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "cparser.l"
{ CParserCount(TT_RBRACK); return(']'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 119 "cparser.l"
{ CParserCount(TT_PERIOD); return('.'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "cparser.l"
{ CParserCount(TT_AMPERSAND); return('&'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "cparser.l"
{ CParserCount(TT_EXCLAMATION); return('!'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "cparser.l"
{ CParserCount(TT_TILDE); return('~'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "cparser.l"
{ CParserCount(TT_MINUS); return('-'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "cparser.l"
{ CParserCount(TT_PLUS); return('+'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "cparser.l"
{ CParserCount(TT_ASTERISK); return('*'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 126 "cparser.l"
{ CParserCount(TT_SLASH); return('/'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 127 "cparser.l"
{ CParserCount(TT_PERCENT); return('%'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 128 "cparser.l"
{ CParserCount(TT_LT); return('<'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 129 "cparser.l"
{ CParserCount(TT_GT); return('>'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "cparser.l"
{ CParserCount(TT_CIRCUMFLEX); return('^'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "cparser.l"
{ CParserCount(TT_VBAR); return('|'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 132 "cparser.l"
{ CParserCount(TT_QUESTION); return('?'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 134 "cparser.l"
{ CParserCount(TT_NOT_A_TOKEN); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 135 "cparser.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 137 "cparser.l"
ECHO;
	YY_BREAK
#line 1280 "lex.cparser.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 243 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 243 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 242);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 137 "cparser.l"


int cparserwrap()
{
        return(1);
}


static void CParserHash()
{
        while ('\n' != input());
}

static void CParserComment()
{
        char c, c1;

        putchar('/'); putchar('*'); /* gdc: added */
loop:
        while ((c = input()) != '*' && c != 0)
                putchar(c);

        if ((c1 = input()) != '/' && c != 0)
        {
                unput(c1);
                goto loop;
        }

        if (c != 0)
                putchar(c); /* gdc: added */
                putchar(c1);
}

int cparser_line = 0;
int cparser_column = 0;

static void CParserCount(TokenType tt)
{
        int i;

        /* This was added to define the semantic value of the current yytext */
        if (TT_NOT_A_TOKEN != tt) /* Used to indicate whitespace... */
           {          
                cparserlval = CParserNewToken(cparser_line, cparser_column,
                                              cparserleng, cparsertext, tt);
           }

        for (i = 0; cparsertext[i] != '\0'; i++)
                if (cparsertext[i] == '\n') {
                        cparser_column = 0;
                        cparser_line++;
                }
                else if (cparsertext[i] == '\t')
                        cparser_column += 8 - (cparser_column % 8);
                else
                        cparser_column++;

        ECHO;
}

/*
* pseudo code --- this is what it should check
*
*       if (cparsertext == type_name)
*               return(TYPE_NAME);
*
*       return(IDENTIFIER);
*/

static int CParserCheckType()
{
    char * name = (char *)malloc(cparserleng + 1);
    strncpy(name, cparsertext, cparserleng);
    name[cparserleng] = '\0';

    if (inNamespace(name))
     {
        cparserlval->tokType = TT_TYPE_NAME;
        return(TYPE_NAME);
     }
    else
     {
        return(IDENTIFIER);
     }
}
